Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: disable

Naming/VariableNumber:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]
